export const FORSTA_PANELLIST = {
  FULLNAME: 'fullName',
  EMAIL: 'email',
  PASSWORD: 'Password',
  LIFESTYLE_SURVEY_UPDATE_FLAG: 'lifestyleSurveyUpdateFlag',
  UPDATE_PROFILE_FLAG: 'UpdateProfileFlag',
  DATE_WHEN_MEMBERSHIP_STARTED: 'dateWhenMembershipStarted',
  SOURCE: 'source',
  CAMPAIGN_ID: 'campaignId',
  UTM_CODE: 'utmCode',
  SOURCE_OTHERS: 'sourceOthers',
  MEMBERSHIP_STATUS: 'membershipStatus',
  DATE_OF_BIRTH: 'dateOfBirth',
  MOBILE_NUMBER: 'mobileNumber',
  GENDER: 'gender',
  RACE: 'race',
  CITIZENSHIP: 'citizenship',
  MARITAL_STATUS: 'maritalStatus',
  SMS_NOTIFICATION: 'smsNotification',
  NEWS_AND_UPDATE: 'newsAndUpdatesViaEmail',
  UPDATE_PROFILE_DATE: 'updateProfileDate',
  RACE_DETAILED: 'raceDetailed',
  LANGUAGE: 'language',
  RETURN_URL: 'returnUrl',
  UPDATE_PROFILE_PROJECT_ID: 'updateProfileProjectid',
} as const;
